### ISSUE TITLE
Port for AngularJS

### ISSUE THREAD

**Issue by prajwalkman** [documentcloud/visualsearch#101]
This isn't really an issue; just a shout out to check if anyone is interested in helping me port this to AngularJS. To me it's both a learning exercise, and to test how far Angular can be taken without jQuery.
I've started on this actually, it probably even has a better base (my implementation can take more than 2 levels of menus), but the UI implementation really has me flummoxed. If anyone is interested do PM me.

My essential goals for the implementation over what is already achieved by this library, is
1. more than 2 levels of menus (eg: Age > greater than > 30)
2. "saved facets" box beside the search bar, they can just add facets onto the search bar from it

**Comment by amcdnl** [comment]
Did anyone port this?

**Comment by escapedcat** [comment]
good share @amcdnl

**Comment by tangokhi** [comment]
Did anyone port it to angular ?
