### ISSUE TITLE
Display Label instead of Value in the box

### ISSUE THREAD

**Issue by mrchief** [documentcloud/visualsearch#52]
Currently label is shown in the menu and value is shown in the box (once something is selected).

It'd great to have the option to display the label instead (to increase the user friendliness). The value should also be retained in the model as that can be used for creating queries.

**Comment by fabarea** [comment]
Sad! Looking at the SearchFacet model, it almost looks as this feature was foreseen.

```
  // If provided, use a custom label instead of the raw value.
  label : function() {
      return this.get('label') || this.get('value');
  }
```
